name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifiez le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurez Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Installez les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Exécutez les tests et mesurez la couverture
    - name: Run tests and coverage
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing

    # 5. Upload du rapport de couverture pour consultation
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    # (Optionnel) 6. Publier les résultats sur un tableau de bord (Codecov)
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Ajoutez ce secret dans les paramètres GitHub
        files: coverage.xml
        flags: unittests
        name: code-coverage

