name: Test and Coverage Workflow

on: [push, pull_request]  # Exécuter le workflow sur chaque push ou pull request
jobs:
  run-tests:
    runs-on: ubuntu-latest  # Exécuter sur une machine Linux standard

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Télécharger le code source

    - name: Set up Python
      uses: actions/setup-python@v4  # Installer Python
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov  # Installer les dépendances pour les tests

    - name: Run tests and generate coverage
      run: |
        pytest --cov=src --cov-report=term-missing  # Lancer les tests et afficher le coverage
